# lr, grad epoch, factor, num-layers, state, stack, init, period, optimizer
python paddle_bounce.py --model-form gaussian --optimizer-form SARSA --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 2 --train --num-iters 30000 --state-forms prox bounds --state-names Paddle Ball --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --factor 20 --num-layers 2 --greedy-epsilon 1 --lr 1e-3 --normalize --behavior-policy egq --optim base --period .04 --reward-form bounce --gamma .99 --grad-epoch 2 --greedy-epsilon-decay 800 --init-form xnorm --save-dir ../datasets/caleb_data/cotest/gaue3_2_5_20_2_proxbounds_2_xnorm_04_base > gau/out_gaue3_2_5_20_2_proxbounds_2_xnorm_04_base.txt
python paddle_bounce.py --model-form gaussian --optimizer-form SARSA --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 2 --train --num-iters 30000 --state-forms bounds bounds --state-names Paddle Ball --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --factor 20 --num-layers 2 --greedy-epsilon 1 --lr 1e-3 --normalize --behavior-policy egq --optim base --period .04 --reward-form bounce --gamma .99 --grad-epoch 2 --greedy-epsilon-decay 800 --init-form xnorm --save-dir ../datasets/caleb_data/cotest/gaue3_2_5_20_2_bbounds_2_xnorm_04_base > gau/out_gaue3_2_5_20_2_bbounds_2_xnorm_04_base.txt
python paddle_bounce.py --model-form gaussian --optimizer-form SARSA --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 2 --train --num-iters 30000 --state-forms prox --state-names Paddle --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --factor 20 --num-layers 2 --greedy-epsilon 1 --lr 1e-3 --normalize --behavior-policy egq --optim base --period .04 --reward-form bounce --gamma .99 --grad-epoch 2 --greedy-epsilon-decay 800 --init-form xnorm --save-dir ../datasets/caleb_data/cotest/gaue3_2_5_20_2_prox_2_xnorm_04_base > gau/out_gaue3_2_5_20_2_prox_2_xnorm_04_base.txt
python paddle_bounce.py --model-form gaussian --optimizer-form SARSA --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 1 --train --num-iters 30000 --state-forms prox bounds vel --state-names Paddle Ball Ball --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --factor 20 --num-layers 2 --greedy-epsilon 1 --lr 1e-3 --normalize --behavior-policy egq --optim base --period .04 --reward-form bounce --gamma .99 --grad-epoch 2 --greedy-epsilon-decay 800 --init-form xnorm --save-dir ../datasets/caleb_data/cotest/gaue3_2_5_20_2_prox_bounds_vel_1_xnorm_04_base > gau/out_gaue3_2_5_20_2_prox_bounds_vel_1_xnorm_04_base.txt
python paddle_bounce.py --model-form gaussian --optimizer-form SARSA --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 1 --train --num-iters 30000 --state-forms prox vel --state-names Paddle Ball --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --factor 20 --num-layers 1 --greedy-epsilon 1 --lr 1e-3 --normalize --behavior-policy egq --optim base --period .04 --reward-form bounce --gamma .99 --grad-epoch 2 --greedy-epsilon-decay 800 --init-form xnorm --save-dir ../datasets/caleb_data/cotest/gaue3_2_5_20_2_prox_vel_1_xnorm_04_base > gau/out_gaue3_2_5_16_1_prox_vel_1_xnorm_04_base.txt
python paddle_bounce.py --model-form gaussian --optimizer-form SARSA --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 2 --train --num-iters 30000 --state-forms prox bounds --state-names Paddle Ball --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --factor 20 --num-layers 2 --greedy-epsilon 1 --lr 1e-3 --normalize --behavior-policy egq --optim base --period .04 --reward-form bounce --gamma .99 --grad-epoch 2 --greedy-epsilon-decay 800 --init-form xnorm --save-dir ../datasets/caleb_data/cotest/gaue3_2_5_20_2_proxbounds_2_xnorm_04_base > gau/out_gaue3_2_5_20_2_proxbounds_2_xnorm_04_base_2.txt
python paddle_bounce.py --model-form gaussian --optimizer-form SARSA --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 2 --train --num-iters 30000 --state-forms bounds bounds --state-names Paddle Ball --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --factor 20 --num-layers 2 --greedy-epsilon 1 --lr 1e-3 --normalize --behavior-policy egq --optim base --period .04 --reward-form bounce --gamma .99 --grad-epoch 2 --greedy-epsilon-decay 800 --init-form xnorm --save-dir ../datasets/caleb_data/cotest/gaue3_2_5_20_2_bbounds_2_xnorm_04_base > gau/out_gaue3_2_5_20_2_bbounds_2_xnorm_04_base_2.txt
python paddle_bounce.py --model-form gaussian --optimizer-form SARSA --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 2 --train --num-iters 30000 --state-forms prox --state-names Paddle --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --factor 20 --num-layers 2 --greedy-epsilon 1 --lr 1e-3 --normalize --behavior-policy egq --optim base --period .04 --reward-form bounce --gamma .99 --grad-epoch 2 --greedy-epsilon-decay 800 --init-form xnorm --save-dir ../datasets/caleb_data/cotest/gaue3_2_5_20_2_prox_2_xnorm_04_base > gau/out_gaue3_2_5_20_2_prox_2_xnorm_04_base_2.txt
python paddle_bounce.py --model-form gaussian --optimizer-form SARSA --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 1 --train --num-iters 30000 --state-forms prox bounds vel --state-names Paddle Ball Ball --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --factor 20 --num-layers 2 --greedy-epsilon 1 --lr 1e-3 --normalize --behavior-policy egq --optim base --period .04 --reward-form bounce --gamma .99 --grad-epoch 2 --greedy-epsilon-decay 800 --init-form xnorm --save-dir ../datasets/caleb_data/cotest/gaue3_2_5_20_2_prox_bounds_vel_1_xnorm_04_base > gau/out_gaue3_2_5_20_2_prox_bounds_vel_1_xnorm_04_base_2.txt
python paddle_bounce.py --model-form gaussian --optimizer-form SARSA --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 1 --train --num-iters 30000 --state-forms prox vel --state-names Paddle Ball --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --factor 20 --num-layers 2 --greedy-epsilon 1 --lr 1e-3 --normalize --behavior-policy egq --optim base --period .04 --reward-form bounce --gamma .99 --grad-epoch 2 --greedy-epsilon-decay 800 --init-form xnorm --save-dir ../datasets/caleb_data/cotest/gaue3_2_5_20_2_prox_vel_1_xnorm_04_base > gau/out_gaue3_2_5_20_2_prox_vel_1_xnorm_04_base_2.txt

python paddle_bounce.py --model-form gaussian --optimizer-form SARSA --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 2 --train --num-iters 30000 --state-forms prox --state-names Paddle --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --factor 20 --num-layers 2 --greedy-epsilon 1 --lr 1e-3 --normalize --behavior-policy egq --optim base --period .01 --reward-form bounce --gamma .99 --grad-epoch 2 --greedy-epsilon-decay 800 --init-form xnorm --save-dir ../datasets/caleb_data/cotest/gaue3_2_5_20_2_prox_2_xnorm_01_base > gau/out_gaue3_2_5_20_2_prox_2_xnorm_01_base.txt
python paddle_bounce.py --model-form gaussian --optimizer-form SARSA --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 2 --train --num-iters 30000 --state-forms prox --state-names Paddle --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --factor 20 --num-layers 2 --greedy-epsilon 1 --lr 1e-3 --normalize --behavior-policy egq --optim base --period .02 --reward-form bounce --gamma .99 --grad-epoch 2 --greedy-epsilon-decay 800 --init-form xnorm --save-dir ../datasets/caleb_data/cotest/gaue3_2_5_20_2_prox_2_xnorm_01_base > gau/out_gaue3_2_5_20_2_prox_2_xnorm_02_base.txt
python paddle_bounce.py --model-form gaussian --optimizer-form SARSA --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 2 --train --num-iters 30000 --state-forms prox --state-names Paddle --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --factor 20 --num-layers 2 --greedy-epsilon 1 --lr 1e-3 --normalize --behavior-policy egq --optim base --period .005 --reward-form bounce --gamma .99 --grad-epoch 2 --greedy-epsilon-decay 800 --init-form xnorm --save-dir ../datasets/caleb_data/cotest/gaue3_2_5_20_2_prox_2_xnorm_005_base > gau/out_gaue3_2_5_20_2_prox_2_xnorm_005_base.txt
python paddle_bounce.py --model-form gaussian --optimizer-form SARSA --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 2 --train --num-iters 30000 --state-forms prox --state-names Paddle --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --factor 20 --num-layers 2 --greedy-epsilon 1 --lr 1e-3 --normalize --behavior-policy egq --optim base --period .05 --reward-form bounce --gamma .99 --grad-epoch 2 --greedy-epsilon-decay 800 --init-form xnorm --save-dir ../datasets/caleb_data/cotest/gaue3_2_5_20_2_prox_2_xnorm_05_base > gau/out_gaue3_2_5_20_2_prox_2_xnorm_05_base.txt
python paddle_bounce.py --model-form gaussian --optimizer-form SARSA --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 2 --train --num-iters 30000 --state-forms prox --state-names Paddle --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --factor 20 --num-layers 2 --greedy-epsilon 1 --lr 1e-3 --normalize --behavior-policy egq --optim base --period .1 --reward-form bounce --gamma .99 --grad-epoch 2 --greedy-epsilon-decay 800 --init-form xnorm --save-dir ../datasets/caleb_data/cotest/gaue3_2_5_20_2_prox_2_xnorm_1_base > gau/out_gaue3_2_5_20_2_prox_2_xnorm_1_base.txt


python paddle_bounce.py --model-form gaussian --optimizer-form SARSA --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 2 --train --num-iters 30000 --state-forms prox --state-names Paddle --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --factor 30 --num-layers 2 --greedy-epsilon 1 --lr 1e-3 --normalize --behavior-policy egq --optim base --period .04 --reward-form bounce --gamma .99 --grad-epoch 2 --greedy-epsilon-decay 800 --init-form xnorm --save-dir ../datasets/caleb_data/cotest/gaue3_2_5_30_2_prox_2_xnorm_04_base > gau/out_gaue3_2_5_30_2_prox_2_xnorm_04_base.txt
python paddle_bounce.py --model-form gaussian --optimizer-form SARSA --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 2 --train --num-iters 30000 --state-forms prox --state-names Paddle --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --factor 10 --num-layers 2 --greedy-epsilon 1 --lr 1e-3 --normalize --behavior-policy egq --optim base --period .04 --reward-form bounce --gamma .99 --grad-epoch 2 --greedy-epsilon-decay 800 --init-form xnorm --save-dir ../datasets/caleb_data/cotest/gaue3_2_5_10_2_prox_2_xnorm_04_base > gau/out_gaue3_2_5_10_2_prox_2_xnorm_04_base.txt
python paddle_bounce.py --model-form gaussian --optimizer-form SARSA --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 2 --train --num-iters 30000 --state-forms prox --state-names Paddle --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --factor 20 --num-layers 1 --greedy-epsilon 1 --lr 1e-3 --normalize --behavior-policy egq --optim base --period .04 --reward-form bounce --gamma .99 --grad-epoch 2 --greedy-epsilon-decay 800 --init-form xnorm --save-dir ../datasets/caleb_data/cotest/gaue3_2_5_20_1_prox_2_xnorm_04_base > gau/out_gaue3_2_5_20_1_prox_2_xnorm_04_base.txt
python paddle_bounce.py --model-form gaussian --optimizer-form SARSA --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 2 --train --num-iters 30000 --state-forms prox --state-names Paddle --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --factor 50 --num-layers 1 --greedy-epsilon 1 --lr 1e-3 --normalize --behavior-policy egq --optim base --period .04 --reward-form bounce --gamma .99 --grad-epoch 2 --greedy-epsilon-decay 800 --init-form xnorm --save-dir ../datasets/caleb_data/cotest/gaue3_2_5_50_1_prox_2_xnorm_04_base > gau/out_gaue3_2_5_50_1_prox_2_xnorm_04_base.txt
python paddle_bounce.py --model-form gaussian --optimizer-form SARSA --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 2 --train --num-iters 30000 --state-forms prox --state-names Paddle --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --factor 10 --num-layers 3 --greedy-epsilon 1 --lr 1e-3 --normalize --behavior-policy egq --optim base --period .04 --reward-form bounce --gamma .99 --grad-epoch 2 --greedy-epsilon-decay 800 --init-form xnorm --save-dir ../datasets/caleb_data/cotest/gaue3_2_5_10_3_prox_2_xnorm_04_base > gau/out_gaue3_2_5_10_3_prox_2_xnorm_04_base.txt
python paddle_bounce.py --model-form gaussian --optimizer-form SARSA --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 2 --train --num-iters 30000 --state-forms prox --state-names Paddle --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --factor 20 --num-layers 2 --greedy-epsilon 1 --lr 1e-3 --normalize --behavior-policy egq --optim base --period .04 --reward-form bounce --gamma .99 --grad-epoch 2 --greedy-epsilon-decay 800 --init-form xnorm --save-dir ../datasets/caleb_data/cotest/gaue3_2_5_20_2_prox_2_xnorm_04_base > gau/out_gaue3_2_5_20_2_prox_2_xnorm_04_base.txt

python paddle_bounce.py --model-form gaussian --optimizer-form SARSA --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 2 --train --num-iters 30000 --state-forms prox --state-names Paddle --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --factor 20 --num-layers 2 --greedy-epsilon 1 --lr 1e-2 --normalize --behavior-policy egq --optim base --period .04 --reward-form bounce --gamma .99 --grad-epoch 2 --greedy-epsilon-decay 800 --init-form xnorm --save-dir ../datasets/caleb_data/cotest/gaue2_2_5_20_2_prox_2_xnorm_04_base > gau/out_gaue2_2_5_20_2_prox_2_xnorm_04_base.txt
python paddle_bounce.py --model-form gaussian --optimizer-form SARSA --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 2 --train --num-iters 30000 --state-forms prox --state-names Paddle --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --factor 20 --num-layers 2 --greedy-epsilon 1 --lr 1e-4 --normalize --behavior-policy egq --optim base --period .04 --reward-form bounce --gamma .99 --grad-epoch 2 --greedy-epsilon-decay 800 --init-form xnorm --save-dir ../datasets/caleb_data/cotest/gaue4_2_5_20_2_prox_2_xnorm_04_base > gau/out_gaue4_2_5_20_2_prox_2_xnorm_04_base.txt
python paddle_bounce.py --model-form gaussian --optimizer-form SARSA --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 2 --train --num-iters 30000 --state-forms prox --state-names Paddle --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --factor 20 --num-layers 2 --greedy-epsilon 1 --lr 1e-5 --normalize --behavior-policy egq --optim base --period .04 --reward-form bounce --gamma .99 --grad-epoch 2 --greedy-epsilon-decay 800 --init-form xnorm --save-dir ../datasets/caleb_data/cotest/gaue5_2_5_20_2_prox_2_xnorm_04_base > gau/out_gaue5_2_5_20_2_prox_2_xnorm_04_base.txt

python paddle_bounce.py --model-form gaussian --optimizer-form SARSA --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 2 --train --num-iters 30000 --state-forms prox --state-names Paddle --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --factor 20 --num-layers 2 --greedy-epsilon 1 --lr 1e-3 --normalize --behavior-policy egq --optim base --period .04 --reward-form bounce --gamma .99 --grad-epoch 5 --greedy-epsilon-decay 800 --init-form xnorm --save-dir ../datasets/caleb_data/cotest/gaue3_5_5_20_2_prox_2_xnorm_04_base > gau/out_gaue3_5_5_20_2_prox_2_xnorm_04_base.txt
python paddle_bounce.py --model-form gaussian --optimizer-form SARSA --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 2 --train --num-iters 30000 --state-forms prox --state-names Paddle --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --factor 20 --num-layers 2 --greedy-epsilon 1 --lr 1e-3 --normalize --behavior-policy egq --optim base --period .04 --reward-form bounce --gamma .99 --grad-epoch 10 --greedy-epsilon-decay 800 --init-form xnorm --save-dir ../datasets/caleb_data/cotest/gaue3_10_5_20_2_prox_2_xnorm_04_base > gau/out_gaue3_10_5_20_2_prox_2_xnorm_04_base.txt
python paddle_bounce.py --model-form gaussian --optimizer-form SARSA --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 2 --train --num-iters 30000 --state-forms prox --state-names Paddle --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --factor 20 --num-layers 2 --greedy-epsilon 1 --lr 1e-3 --normalize --behavior-policy egq --optim base --period .04 --reward-form bounce --gamma .99 --grad-epoch 1 --greedy-epsilon-decay 800 --init-form xnorm --save-dir ../datasets/caleb_data/cotest/gaue3_1_5_20_2_prox_2_xnorm_04_base > gau/out_gaue3_1_5_20_2_prox_2_xnorm_04_base.txt

python paddle_bounce.py --model-form gaussian --optimizer-form SARSA --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 2 --train --num-iters 30000 --state-forms prox --state-names Paddle --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --factor 20 --num-layers 2 --greedy-epsilon 1 --lr 1e-3 --normalize --behavior-policy egq --optim Adam --period .04 --reward-form bounce --gamma .99 --grad-epoch 2 --greedy-epsilon-decay 800 --init-form xnorm --save-dir ../datasets/caleb_data/cotest/gaue3_2_5_20_2_prox_2_xnorm_04_Adam > gau/out_gaue3_2_5_20_2_prox_2_xnorm_04_Adam.txt
python paddle_bounce.py --model-form gaussian --optimizer-form SARSA --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 2 --train --num-iters 30000 --state-forms prox --state-names Paddle --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --factor 20 --num-layers 2 --greedy-epsilon 1 --lr 1e-3 --normalize --behavior-policy egq --optim RMSprop --period .04 --reward-form bounce --gamma .99 --grad-epoch 2 --greedy-epsilon-decay 800 --init-form xnorm --save-dir ../datasets/caleb_data/cotest/gaue3_2_5_20_2_prox_2_xnorm_04_RMSprop > gau/out_gaue3_2_5_20_2_prox_2_xnorm_04_RMSprop.txt

python paddle_bounce.py --model-form gaussian --optimizer-form SARSA --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 2 --train --num-iters 30000 --state-forms prox --state-names Paddle --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --factor 20 --num-layers 2 --greedy-epsilon 1 --lr 1e-3 --normalize --behavior-policy egq --optim base --period .04 --reward-form bounce --gamma .99 --grad-epoch 2 --greedy-epsilon-decay 800 --init-form xuni --save-dir ../datasets/caleb_data/cotest/gaue3_2_5_20_2_prox_2_xuni_04_base > gau/out_gaue3_2_5_20_2_prox_2_xuni_04_base.txt
python paddle_bounce.py --model-form gaussian --optimizer-form SARSA --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 2 --train --num-iters 30000 --state-forms prox --state-names Paddle --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --factor 20 --num-layers 2 --greedy-epsilon 1 --lr 1e-3 --normalize --behavior-policy egq --optim base --period .04 --reward-form bounce --gamma .99 --grad-epoch 2 --greedy-epsilon-decay 800 --init-form uni --save-dir ../datasets/caleb_data/cotest/gaue3_2_5_20_2_prox_2_uni_04_base > gau/out_gaue3_2_5_20_2_prox_2_uni_04_base.txt

