# grad epochs, state, stack
python paddle_bounce.py --model-form tab --optimizer-form TabQ --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 2 --train --num-iters 100000 --state-forms prox --state-names Paddle --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --greedy-epsilon 1 --behavior-policy egq --optim base --reward-form bounce --gamma .99 --buffer-steps 10000 --num-grad-states 5 --grad-epoch 2 --greedy-epsilon-decay 1000 --lr 1e-3 --save-recycle 10000 --save-dir ../datasets/caleb_data/cotest/tabular_ge2_5_prox_2 > tabular/out_ge2_5_prox_2.txt
python paddle_bounce.py --model-form tab --optimizer-form TabQ --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 2 --train --num-iters 100000 --state-forms prox bounds --state-names Paddle Ball --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --greedy-epsilon 1 --behavior-policy egq --optim base --reward-form bounce --gamma .99 --buffer-steps 10000 --num-grad-states 5 --grad-epoch 2 --greedy-epsilon-decay 1000 --lr 1e-3 --save-recycle 10000 --save-dir ../datasets/caleb_data/cotest/tabular_ge2_5_proxbounds_2 > tabular/out_ge2_5_proxbounds_2.txt
python paddle_bounce.py --model-form tab --optimizer-form TabQ --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 2 --train --num-iters 100000 --state-forms xprox --state-names Paddle --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --greedy-epsilon 1 --behavior-policy egq --optim base --reward-form bounce --gamma .99 --buffer-steps 10000 --num-grad-states 5 --grad-epoch 2 --greedy-epsilon-decay 1000 --lr 1e-3 --save-recycle 10000 --save-dir ../datasets/caleb_data/cotest/tabular_ge2_5_prox > tabular/out_ge2_5_xprox_2.txt
python paddle_bounce.py --model-form tab --optimizer-form TabQ --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 1 --train --num-iters 100000 --state-forms prox --state-names Paddle --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --greedy-epsilon 1 --behavior-policy egq --optim base --reward-form bounce --gamma .99 --buffer-steps 10000 --num-grad-states 5 --grad-epoch 2 --greedy-epsilon-decay 1000 --lr 1e-3 --save-recycle 10000 --save-dir ../datasets/caleb_data/cotest/tabular_ge2_5_prox > tabular/out_ge2_5_prox_1.txt
python paddle_bounce.py --model-form tab --optimizer-form TabQ --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 1 --train --num-iters 100000 --state-forms prox --state-names Paddle --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --greedy-epsilon 1 --behavior-policy egq --optim base --reward-form bounce --gamma .99 --buffer-steps 10000 --num-grad-states 5 --grad-epoch 2 --greedy-epsilon-decay 1000 --lr 1e-3 --save-recycle 10000 --save-dir ../datasets/caleb_data/cotest/tabular_ge2_5_prox > tabular/out_ge2_5_prox_1.txt
python paddle_bounce.py --model-form tab --optimizer-form TabQ --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 1 --train --num-iters 100000 --state-forms prox --state-names Paddle --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --greedy-epsilon 1 --behavior-policy egq --optim base --reward-form bounce --gamma .99 --buffer-steps 10000 --num-grad-states 5 --grad-epoch 10 --greedy-epsilon-decay 1000 --lr 1e-3 --save-recycle 10000 --save-dir ../datasets/caleb_data/cotest/tabular_ge10_5_prox > tabular/out_ge10_5_prox_1.txt
python paddle_bounce.py --model-form tab --optimizer-form TabQ --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 1 --train --num-iters 100000 --state-forms prox --state-names Paddle --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --greedy-epsilon 1 --behavior-policy egq --optim base --reward-form bounce --gamma .99 --buffer-steps 10000 --num-grad-states 5 --grad-epoch 5 --greedy-epsilon-decay 1000 --lr 1e-3 --save-recycle 10000 --save-dir ../datasets/caleb_data/cotest/tabular_ge5_5_prox > tabular/out_ge5_5_prox_1.txt
python paddle_bounce.py --model-form tab --optimizer-form TabQ --record-rollouts "data/action/" --train-edge "Paddle->Ball" --num-stack 1 --train --num-iters 100000 --state-forms prox --state-names Paddle --base-node Paddle --changepoint-dir ../datasets/caleb_data/cotest/paddlegraph --greedy-epsilon 1 --behavior-policy egq --optim base --reward-form bounce --gamma .99 --buffer-steps 10000 --num-grad-states 5 --grad-epoch 1 --greedy-epsilon-decay 1000 --lr 1e-3 --save-recycle 10000 --save-dir ../datasets/caleb_data/cotest/tabular_ge1_5_prox > tabular/out_ge1_5_prox_1.txt

